Towards creating a documenation page
TheELNConsortium/TheELNFileFormat pull request #110
Opened 2024-12-09 08:03 UTC by SteffenBrinckmann

We talked in the Nov. 2024 meeting about creating screenshots after importing the .eln to showcase that importing / interoperability works. (An example of all imports passing the github actions is shown for PASTA)

Here a suggestion of how that could be presented:
- using the documentation framework and sphinx
- each importing partner puts their screenshots and an index file into a separate folder (like the example folder for exported .eln)
- a link is placed in the central index (which can have more information: specification ...)

To build from the repository directory (the one with .git)
- make -C docs html
- firefox docs/build/html/index.html

The build and publication process can be created as github action, but that would need to be discussed.

What do you think?

2024-12-09 10:43 UTC, SteffenBrinckmann commented
@dalito Thanks for feedback. Did that update

2024-12-09 16:17 UTC, NicolasCARPi requested changes
Didn't try to build the doc yet, just added a few comments. Please hold merge until we agree on things here.

Things we can agree on: the use of sphinx seems the best option for this kind of project.

2024-12-09 16:17 UTC, NicolasCARPi commented on .gitignore
> +examples/*/*/
I don't unsterstand this line

2024-12-09 16:17 UTC, NicolasCARPi commented on docs/Makefile
> +.PHONY: help Makefile
is this makefile correct? For reference, a complete one: https://github.com/elabftw/elabdoc/blob/master/doc/Makefile

seems the `.PHONY:` line is missing `html` target at least

2024-12-09 16:17 UTC, NicolasCARPi commented on docs/README.md
> +make -C docs html
can we make it so just `make html` works?

2024-12-09 16:17 UTC, NicolasCARPi commented on docs/make.bat
> +@ECHO OFF
can we remove any windows related stuff? don't care about it. don't want to have to maintain a windows script. users nowadays will use WSL anyway, let's not pollute our codebase with .bat files.

2024-12-09 16:17 UTC, NicolasCARPi commented on docs/requirements.txt
> +sphinx_rtd_theme
please pin to exact version

2024-12-10 11:05 UTC, SteffenBrinckmann commented on .gitignore
> +examples/*/*/
Conveniently, ignore sub sub folders of examples. 
Allows to unzip into folders, and git not caring
Not important for docs

2024-12-10 11:10 UTC, SteffenBrinckmann commented on docs/Makefile
> +.PHONY: help Makefile
This makefile was autobuild by sphinx and not modified by me. One should only modify the conf.py file, as I did.
Seems different sphinx versions autocreate different makefile.

2024-12-10 11:12 UTC, SteffenBrinckmann commented on docs/README.md
> +make -C docs html
Sure we can modify it. 
Currently
- in root folder add the -c option or
- in docs folder, just make

2024-12-10 11:14 UTC, SteffenBrinckmann commented on docs/Makefile
> +.PHONY: help Makefile
We can change that on the final version. This is just preview to have discussion at next meeting.

2024-12-10 11:14 UTC, SteffenBrinckmann commented on docs/README.md
> +make -C docs html
We can change that on the final version. This is just preview to have discussion at next meeting.

2024-12-10 11:16 UTC, SteffenBrinckmann commented on docs/requirements.txt
> +sphinx_rtd_theme
We can change that on the final version. This is just preview to have discussion at next meeting.

2024-12-10 11:50 UTC, NicolasCARPi commented on .gitignore
> +examples/*/*/
I see, but what if we want to track a subfolder in there later? I think this is a wrong solution. The gitignore file must not be polluted by such ad-hoc lines that are not evident to understand why it's here. I suggest removing this line: as long as the files are not tracked by git, git will leave them alone, so there is no need to have this.

(also, if you absolutely want to keep it, I won't lose sleep over it)

2025-01-17 12:24 UTC, SteffenBrinckmann commented on docs/requirements.txt
> +sphinx_rtd_theme
Did that: "pip freeze" all requirements for 100% reproducibility

2025-01-17 12:24 UTC, SteffenBrinckmann commented on docs/make.bat
> +@ECHO OFF
File is gone

2025-01-17 12:25 UTC, SteffenBrinckmann commented on docs/README.md
> +make -C docs html
I tested and verified: if you go into docs: "make html" does everything

2025-01-17 12:26 UTC, SteffenBrinckmann commented on .gitignore
> +examples/*/*/
Reversed that change

2025-01-17 12:29 UTC, SteffenBrinckmann commented
I took the workflow from the static pull-request #111  and added some lines in the middle: these lines build html pages.

2025-01-17 13:30 UTC, NicolasCARPi approved these changes

2025-01-17 17:01 UTC, merged