Update Specification
TheELNConsortium/TheELNFileFormat pull request #75
Opened 2024-06-12 13:38 UTC by jmanideep

I have updated the specification to clarify the properties each object type should have. Please review the changes and provide any feedback.

- **Dataset Objects (`@type: Dataset`)**
  - **Properties:** `name`, `author` (should include).
  - **Optional Properties:** `identifier`, `dateCreated`, `dateModified`, `text`, `keywords`, `comment`.
  - **Additional Files:** If a Dataset object contains additional files, they should be listed in its `hasPart` property and can be referenced through their `@id`.

- **File Objects (`@type: File`)**
  - **Properties:** `name`, `encodingFormat`, `contentSize` (should include).
  - **Optional Properties:** `description`, `sha256`, `author`, `identifier`, `dateCreated`, `dateModified`, `text`.

- **Organization Entities**
  - **Properties:** `@id`, `@type: Organization`, `name`, `url` (should include)
  - **Optional Properties:** Other properties from the `Organization`.

Please review the changes and let me know if you have any questions or suggestions.

2024-06-12 13:50 UTC, NicolasCARPi commented on SPECIFICATION.md
> +```yaml
what's wrong with using `~` ?

2024-06-12 13:52 UTC, NicolasCARPi commented on SPECIFICATION.md
> +If a Dataset object (node) has additional files, they should be listed in its `hasPart` property and can be referenced through their `@id`.
I suggest using exclusively **node** terminology. With a sentence explaining what is a `node` in the context of the JSON-LD graph.

2024-06-12 14:10 UTC, jmanideep commented on SPECIFICATION.md
> +```yaml
The formatting was automatically adjusted by Black.

2024-06-12 14:12 UTC, NicolasCARPi commented on SPECIFICATION.md
> +```yaml
Oh okay then, let's leave it like that. I prefer the `~` but let's go with the default choice that was made by black!

2024-06-12 14:16 UTC, nicobrandt commented on SPECIFICATION.md
> +```yaml
I don't think black formats Markdown, must have been done by something else. But the new Syntax is more common anyways I think, Github uses it as well in its editor.

2024-06-12 14:54 UTC, jmanideep commented on SPECIFICATION.md
> +If a Dataset object (node) has additional files, they should be listed in its `hasPart` property and can be referenced through their `@id`.
Used node terminology wherever possible and also added a sentence explaining what a `node` is.

2024-06-12 15:49 UTC, NicolasCARPi requested changes

2024-06-12 15:49 UTC, NicolasCARPi commented on SPECIFICATION.md
> +  "sdPublisher": [
sdPublisher value is not an array, it should be:

~~~json
"sdPublisher": {"@id": "https://eln-example.com"},
~~~

2024-06-13 09:59 UTC, NicolasCARPi approved these changes

2024-06-15 14:18 UTC, merged