AI4Green example .ELN file
TheELNConsortium/TheELNFileFormat pull request #79
Opened 2024-07-22 08:49 UTC by JoeDavies-6

- Example .ELN file generated from AI4Green
- Readme file with the ro-crate-metadata.json contents

2024-07-22 13:46 UTC, NicolasCARPi requested changes

2024-07-22 13:46 UTC, NicolasCARPi commented on examples/AI4Green/README.md
> +      "comment": [
comment should look like this:

~~~json
 "comment": [
        {
          "@id": "comment-id/AI4-001/5"
        }
      ],
~~~

2024-07-22 13:46 UTC, NicolasCARPi commented on examples/AI4Green/README.md
> +      "emailAddress": "joseph.davies@nottingham.ac.uk"
`emailAddress` is an invalid property, the correct one is simply `email`. See: https://schema.org/email and https://schema.org/Person

2024-07-22 13:46 UTC, NicolasCARPi commented on examples/AI4Green/README.md
> +      "fullName": "Joe Davies",
Split this in `givenName` and `familyName`. See https://schema.org/Person.

2024-07-22 13:46 UTC, NicolasCARPi commented on examples/AI4Green/README.md
> +      "contentSize": "853054",
`contentSize` is an number, not a string.

2024-07-22 13:46 UTC, NicolasCARPi commented on examples/AI4Green/README.md
> +      "url": "http://ai4green.app/home/Development-Workgroup/Export%20workbook/AI4-001/no"
http**s**?

2024-07-22 13:51 UTC, NicolasCARPi commented
Hello,

Thank you for submitting this example. Please address my comments.

Unrelated to `.eln`: you store your reaction in a `.rdf` file, which seems like it's some sort of non-standard file format for reactions. Do you think it could be changed or completed by a more standardized format such as `.rxn`?

rdf is a bit problematic and could cause confusion, especially in the context of JSON-LD, see https://www.rfc-editor.org/rfc/rfc3870.html.

So if possible, I would recommend dropping this non-standard extension and use a more standardized format, to increase interoperability, which is our goal here.

2024-07-23 06:55 UTC, nicobrandt commented on examples/AI4Green/README.md
> +      "contentSize": "853054",
It is a string actually https://schema.org/contentSize

2024-07-23 07:06 UTC, jmanideep commented on examples/AI4Green/README.md
> +      "@type": "Dataset",
In the node where `"@id": "./"`, `@type` should be an array of Dataset i.,e `["Dataset"]`.

2024-07-23 07:09 UTC, jmanideep commented on examples/AI4Green/README.md
> +      "sdPublisher": {
All nodes should be flattened, for eg: `sdPublisher`.

2024-07-23 07:11 UTC, jmanideep commented on examples/AI4Green/README.md
> +      "@id": "./AI4-001",
`@id` property in `Dataset` nodes must end with `/`.

2024-07-23 15:53 UTC, NicolasCARPi commented on examples/AI4Green/README.md
> +      "contentSize": "853054",
In fact, there are [discussions](https://github.com/schemaorg/schemaorg/issues/869) about its format, like "2 Gb" or "84120 B". For the .eln, can we all agree to use number of bytes and leave the conversion to the consumer? (so skip the units, because it's not clear what should be used and how).

And yeah, it probably should be a string, although I cannot find a definitive instruction about the type. Given that the schema is uncorrelated to its representation (rdf, json-ld, etc), it's probably fine to use a correct type depending on the kind of value. If we leave out the unit, then having it as "number" is correct. But I could totally agree on using it as string. It doesn't really matter, even if in my view, storing numbers as numbers is more correct.

2024-07-24 07:06 UTC, nicobrandt commented on examples/AI4Green/README.md
> +      "contentSize": "853054",
It's unfortunate that even simple properties like this one leave room for interpretation. Our current examples are at least only split between two versions: number of bytes as number and number of bytes as string. We should just add this on the agenda for the next meeting and agree on one of these :)

2024-07-24 11:31 UTC, NicolasCARPi commented on examples/AI4Green/README.md
> +      "contentSize": "853054",
https://github.com/TheELNConsortium/TheELNFileFormat/discussions/73#discussioncomment-10136748

2024-08-19 14:55 UTC, JoeDavies-6 commented
Apologies for the delay in responding. Thanks for the comments on the first draft. I believe I have addressed all of them, but please let me know if there are any issues that are still outstanding.

2024-08-19 15:03 UTC, NicolasCARPi commented
@JoeDavies-6 Is the .eln in sync with the README changes? For instance, the `comment` seems fixed in the README, but in the JSON metadata it still appears to be incorrect.

In README visible in diff:

![2024-08-19-170210_420x100_scrot](https://github.com/user-attachments/assets/d2a9129a-afa9-4734-a39b-70fc5c2e4102)

In JSON metadata file:

![2024-08-19-170221_361x70_scrot](https://github.com/user-attachments/assets/846c2133-53ef-4bac-8960-3d4f8e52ef5e)

2024-08-27 09:12 UTC, NicolasCARPi commented
ping @JoeDavies-6

2024-08-27 14:25 UTC, JoeDavies-6 commented
> ping @JoeDavies-6

Apologies, I didn't update the .eln file before. I've now updated the .eln file and the README

2024-08-27 15:51 UTC, NicolasCARPi approved these changes
LGTM!

![2024-08-27-175004_1767x903_scrot](https://github.com/user-attachments/assets/d629a4a2-be1b-42e1-aacc-d4ca1f169832)
![2024-08-27-175012_1758x883_scrot](https://github.com/user-attachments/assets/51e2c858-6687-4749-bafa-22dfb614f4ce)
![2024-08-27-175029_1760x608_scrot](https://github.com/user-attachments/assets/5b53781e-9dd1-403c-8bff-5de45d3c7ad1)

2024-08-27 15:52 UTC, merged